# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Sofia Carrera"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
# baseurl = "https://sofiacarrera.com/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
# copyright = ""

# Enable analytics by entering your Google Analytics tracking ID
# googleAnalytics = ""

############################
## Advanced options below ##
############################

[[imports]]
path = "github.com/gethugothemes/hugo-modules/icons/font-awesome"